apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  # namespace: default # can only be used inside this namespace.
type: Opaque # value type: tls,  https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
data:
  # secret need to be BASE64_ENCODED_VALUE  # echo -n 'password' | base 64  // -n do not print newline
  jwt: YWRmcw== # adfs
  mongo-user: cm9vdA== # root
  mongo-password: cGFzc3dvcmQ= # password
