apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: blog
build:
  local:
    push: false
  artifacts:
    - image: bryonsmith/client
      context: client
      docker:
        dockerfile: Dockerfile
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
      #     - src: 'src/**/*.js'
      #       dest: .
      #     - src: 'src/**/*.s?css'
      #       dest: .
      # custom:
      #   buildCommand: ./build.sh client
    - image: bryonsmith/comments
      context: comments
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: '4001'
          NODE_ENV: production
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
    - image: bryonsmith/events
      context: event-bus
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: '4005'
          NODE_ENV: production
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
    - image: bryonsmith/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: '4003'
          NODE_ENV: production
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
    - image: bryonsmith/posts
      context: posts
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: '4000'
          NODE_ENV: production
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
    - image: bryonsmith/query
      context: query
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: '4002'
          NODE_ENV: production
      # sync:
      #   manual:
      #     - src: 'src/**/*.ts'
      #       dest: .
manifests:
  rawYaml:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/events-depl.yaml
    # - infra/k8s/ingress-nginx.yaml
    - infra/k8s/ingress.svc.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/query-depl.yaml
